git:
  commitMessage: "chore(release): v${version}"
  tagAnnotation: "chore(release): v${version}"
  tagName: "v${version}"

npm:
  publish: true
  private: false
  registry: "https://registry.npmjs.org/"

hooks:
  after:bump:
    - "npm run changelog:update"
